theme: jekyll-theme-minimal
title: Candy the Catacorn
description: The homepage of Candy the Catacorn, a MicroPython and PlatformIO compatible blinky-light mini badge with capacitive touch and RGB eyes!
logo: assets/images/CandytheCatacorn.png